### ISSUE TITLE
compilation failure: macros that expand to items must either be surrounded with braces or followed by a semicolon

### ISSUE THREAD

**Issue by bestouff** [deuterium-orm/deuterium#2]

**Comment by s-panferov** [comment]
@bestouff, thanks for your report. I have been refactoring deuterium for the new Rust in #3, but there are **a lot** of changes since I touched it the last time. The library is big so it may take a couple of days to make it work again.

**Comment by bestouff** [comment]
That's OK, I just need it for a toy server I'm trying to do with rustless, and I opened a bug to know when I'm ready to start.
Thanks

**Comment by s-panferov** [comment]
@bestouff I recommend you to start with just rustless + rust-postgres + raw sql. DeuteriumORM is quite unstable and needs a lot of work even after I'll fix it for the new Rust.

**Comment by bestouff** [comment]
OK. Care to fix rustless & rust-postgres compilation then ? I'll do a cargo update and won't touch my deps for a while, I promise :)
Thanks

**Comment by s-panferov** [comment]
@bestouff see example in https://github.com/rustless/rustless/tree/master/examples/postgres. Deuterium was fixed so I close this.

**Comment by bestouff** [comment]
OK, but for me phf_shared still makes the compilation fail with "no_std is experimental".
